[package]
name = "dualcache-ff"
version = "1.1.1"
edition = "2024"
authors = ["hianova"]
description = "A Cache system aim for read more write less"
license = "PolyForm-Noncommercial-1.0.0"
repository = "https://github.com/hianova/DualCache-FF"
readme = "./ReadMe.md"
keywords = ["cache"]

[dependencies]
anyhow=">0"
arc-swap = ">0"
crossbeam = "=0"
ahash = "=0"
