[package]
name = "cache-bench"
version = "0.1.0"
edition = "2024"

[lib]
name = "cache_bench"
path = "src/lib.rs"

[[bench]]
name = "throughput"
harness = false               # 使用 criterion 的异步/自定义主函数

[dependencies]
moka = { version = "0.12", features = ["sync"] }
rand = "0.8"
zipf = "0.2"
dualcache-ff = { path = "../../" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.bench]
debug = true