[package]
name = "cache-bench"
version = "0.1.0"
edition = "2024"

[features]
full_bench = []

[lib]
name = "cache_bench"
path = "src/lib.rs"
bench = false

[[bench]]
name = "throughput"
harness = false               # 使用 criterion 的异步/自定义主函数

[[bench]]
name = "memory"
harness = false               # 自定义 main 函数来测内存

[[bench]]
name = "latency"
harness = false

[[bench]]
name = "capex"
harness = false

[dependencies]
moka = { version = "0.12", features = ["sync"] }
rand = "0.8"
rand_distr = "0.4"          # 新增
dualcache-ff = { path = "../../" }
TinyUFO = "0.8.0"
memory-stats=">0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.bench]
debug = true
